# Generated by Django 4.2.7 on 2026-02-15 16:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("voitures", "0004_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modele",
            name="annee_lancement",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2026),
                ]
            ),
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("reservation", "Réservation véhicule"),
                            ("essai", "Essai"),
                        ],
                        default="reservation",
                        max_length=20,
                    ),
                ),
                ("debut", models.DateTimeField()),
                ("fin", models.DateTimeField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("acceptee", "Acceptée"),
                            ("refusee", "Refusée"),
                            ("annulee", "Annulée"),
                            ("terminee", "Terminée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("signature", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voiture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="voitures.voiture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
                "ordering": ["-date_creation"],
            },
        ),
    ]
