# Generated by Django 4.2.7 on 2026-02-15 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("voitures", "0005_alter_modele_annee_lancement_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiture",
            name="carburant_niveau",
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="voiture",
            name="est_louee",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="voiture",
            name="gps_tracking_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="voiture",
            name="localisation",
            field=models.CharField(default="Dépôt", max_length=120),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debut", models.DateTimeField()),
                ("fin", models.DateTimeField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_venir", "À venir"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("annulee", "Annulée"),
                        ],
                        default="a_venir",
                        max_length=20,
                    ),
                ),
                (
                    "kilometrage_depart",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "carburant_depart",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "kilometrage_retour",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "carburant_retour",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "prix_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("conditions", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voiture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="voitures.voiture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["voiture", "statut", "debut", "fin"],
                        name="voitures_lo_voiture_53e38b_idx",
                    )
                ],
            },
        ),
    ]
